const fs = require('fs');
const path = require('path');

const newReport = {
  en: {
    loading: "Loading report...", error: { title: "Failed to load report", desc: "The report ID may be invalid or you do not have permission to view it.", back: "Return to Dashboard" }, title: "Analysis Report", subtitle: "Crop Analysis", verified: "AI Verified", score: "Score", status: { healthy: "Healthy Crop", severity: "Severity", healthyTitle: "Crop Appears Healthy", healthyDesc: "No significant diseases or pests were detected with high confidence.", detected: "Detected", diseaseDesc: "We detected signs of infection. Immediate action is required to prevent further crop loss and spreading to healthy plants." }, confidence: { title: "AI Confidence Analysis", disease: "Detected disease.", pest: "Detected pest.", none: "No issues detected by the AI." }, recovery: { title: "Recovery Estimate", label: "Expected Recovery In", days: "7 - 10 Days", desc: "If the recommended treatment is applied today, new healthy foliage should appear within a week." }, plan: { title: "Verified Treatment Plan", subtitle: "ICAR Approved Protocol", medicine: { type: "Chemical Fungicide", dosage: "Dosage / Acre", water: "Water / Acre", important: "Important:", warning: "Wait at least 5 days after spraying before harvesting. Wear protective gear." }, why: { title: "Why we recommend this", desc: "Mancozeb is a broad-spectrum contact fungicide that provides excellent preventative action. It is highly recommended by ICAR for this specific stage of crop growth." }, actions: { add: "Add to Today's Tasks", order: "Order Medicine" } }
  },
  hi: {
    loading: "रिपोर्ट लोड हो रही है...", error: { title: "रिपोर्ट लोड करने में विफल", desc: "रिपोर्ट अमान्य हो सकती है।", back: "डैशबोर्ड पर लौटें" }, title: "विश्लेषण रिपोर्ट", subtitle: "फसल विश्लेषण", verified: "AI सत्यापित", score: "स्कोर", status: { healthy: "स्वस्थ फसल", severity: "गंभीरता", healthyTitle: "फसल स्वस्थ प्रतीत होती है", healthyDesc: "कोई बीमारी या कीट नहीं मिला।", detected: "पता चला", diseaseDesc: "हमें संक्रमण के संकेत मिले हैं। तत्काल कार्रवाई की आवश्यकता है।" }, confidence: { title: "AI विश्वास विश्लेषण", disease: "बीमारी मिली।", pest: "कीट मिला।", none: "AI द्वारा कोई समस्या नहीं मिली।" }, recovery: { title: "वसूली अनुमान", label: "अपेक्षित वसूली", days: "7 - 10 दिन", desc: "यदि आज अनुशंसित उपचार लागू किया जाता है, तो एक सप्ताह के भीतर नए स्वस्थ पत्ते दिखाई देने चाहिए।" }, plan: { title: "सत्यापित उपचार योजना", subtitle: "ICAR स्वीकृत प्रोटोकॉल", medicine: { type: "रासायनिक कवकनाशी", dosage: "खुराक / एकड़", water: "पानी / एकड़", important: "महत्वपूर्ण:", warning: "कटाई से पहले कम से कम 5 दिन प्रतीक्षा करें। सुरक्षात्मक गियर पहनें।" }, why: { title: "हम इसकी अनुशंसा क्यों करते हैं", desc: "Mancozeb एक कवकनाशी है जो उत्कृष्ट निवारक कार्रवाई प्रदान करता है।" }, actions: { add: "आज के कार्यों में जोड़ें", order: "दवा मंगाएं" } }
  },
  mr: {
    loading: "अहवाल लोड होत आहे...", error: { title: "अहवाल लोड करण्यात अयशस्वी", desc: "अहवाल अवैध असू शकतो.", back: "डॅशबोर्डवर परत जा" }, title: "विश्लेषण अहवाल", subtitle: "पीक विश्लेषण", verified: "AI सत्यापित", score: "गुण", status: { healthy: "निरोगी पीक", severity: "तीव्रता", healthyTitle: "पीक निरोगी दिसते", healthyDesc: "कोणतेही रोग किंवा कीटक आढळले नाहीत.", detected: "आढळले", diseaseDesc: "आम्हाला संसर्गाची चिन्हे आढळली आहेत. त्वरित कारवाई आवश्यक आहे." }, confidence: { title: "AI आत्मविश्वास विश्लेषण", disease: "रोग आढळला.", pest: "कीटक आढळला.", none: "AI द्वारे कोणतीही समस्या आढळली नाही." }, recovery: { title: "पुनर्प्राप्ती अंदाज", label: "अपेक्षित पुनर्प्राप्ती", days: "7 - 10 दिवस", desc: "आज शिफारस केलेला उपचार लागू केल्यास, एका आठवड्यात नवीन निरोगी पाने दिसतील." }, plan: { title: "सत्यापित उपचार योजना", subtitle: "ICAR मान्यताप्राप्त प्रोटोकॉल", medicine: { type: "रासायनिक बुरशीनाशक", dosage: "डोस / एकर", water: "पाणी / एकर", important: "महत्वाचे:", warning: "काढणीपूर्वी किमान 5 दिवस प्रतीक्षा करा. संरक्षक गियर घाला." }, why: { title: "आम्ही याची शिफारस का करतो", desc: "मॅन्कोझेब एक बुरशीनाशक आहे जे उत्कृष्ट प्रतिबंधात्मक कारवाई प्रदान करते." }, actions: { add: "आजच्या कामांमध्ये जोडा", order: "औषध मागवा" } }
  },
  bn: {
    loading: "রিপোর্ট লোড হচ্ছে...", error: { title: "রিপোর্ট লোড ব্যর্থ", desc: "রিপোর্ট অবৈধ হতে পারে।", back: "ড্যাশবোর্ডে ফিরে যান" }, title: "বিশ্লেষণ রিপোর্ট", subtitle: "ফসল বিশ্লেষণ", verified: "AI যাচাইকৃত", score: "স্কোর", status: { healthy: "সুস্থ ফসল", severity: "তীব্রতা", healthyTitle: "ফসল সুস্থ বলে মনে হচ্ছে", healthyDesc: "কোন রোগ বা কীটপতঙ্গ পাওয়া যায়নি।", detected: "সনাক্ত করা হয়েছে", diseaseDesc: "আমরা সংক্রমণের লক্ষণ সনাক্ত করেছি। অবিলম্বে ব্যবস্থা প্রয়োজন।" }, confidence: { title: "AI আত্মবিশ্বাস বিশ্লেষণ", disease: "রোগ পাওয়া গেছে।", pest: "কীটপতঙ্গ পাওয়া গেছে।", none: "AI দ্বারা কোন সমস্যা সনাক্ত করা যায়নি।" }, recovery: { title: "পুনরুদ্ধারের অনুমান", label: "প্রত্যাশিত পুনরুদ্ধার", days: "7 - 10 দিন", desc: "আজ সুপারিশকৃত চিকিৎসা প্রয়োগ করা হলে, এক সপ্তাহের মধ্যে নতুন সুস্থ পাতা দেখা যাবে।" }, plan: { title: "যাচাইকৃত চিকিৎসা পরিকল্পনা", subtitle: "ICAR অনুমোদিত প্রোটোকল", medicine: { type: "রাসায়নিক ছত্রাকনাশক", dosage: "ডোজ / একর", water: "জল / একর", important: "গুরুত্বপূর্ণ:", warning: "ফসল কাটার আগে কমপক্ষে 5 দিন অপেক্ষা করুন। সুরক্ষামূলক গিয়ার পরিধান করুন।" }, why: { title: "কেন আমরা এটি সুপারিশ করি", desc: "ম্যানকোজেব একটি ছত্রাকনাশক যা চমৎকার প্রতিরোধমূলক ব্যবস্থা প্রদান করে।" }, actions: { add: "আজকের কাজে যোগ করুন", order: "ওষুধ অর্ডার করুন" } }
  },
  ta: {
    loading: "அறிக்கை ஏற்றப்படுகிறது...", error: { title: "அறிக்கையை ஏற்ற முடியவில்லை", desc: "அறிக்கை செல்லாததாக இருக்கலாம்.", back: "முகப்புக்கு திரும்பவும்" }, title: "பகுப்பாய்வு அறிக்கை", subtitle: "பயிர் பகுப்பாய்வு", verified: "AI சரிபார்க்கப்பட்டது", score: "மதிப்பெண்", status: { healthy: "ஆரோக்கியமான பயிர்", severity: "தீவிரம்", healthyTitle: "பயிர் ஆரோக்கியமாக உள்ளது", healthyDesc: "எந்த நோய்களும் பூச்சிகளும் காணப்படவில்லை.", detected: "கண்டறியப்பட்டது", diseaseDesc: "தொற்றுக்கான அறிகுறிகளை நாங்கள் கண்டறிந்துள்ளோம். உடனடி நடவடிக்கை தேவை." }, confidence: { title: "AI நம்பிக்கை பகுப்பாய்வு", disease: "நோய் கண்டறியப்பட்டது.", pest: "பூச்சி கண்டறியப்பட்டது.", none: "AI ஆல் எந்த பிரச்சினையும் கண்டறியப்படவில்லை." }, recovery: { title: "மீட்பு மதிப்பீடு", label: "எதிர்பார்க்கப்படும் மீட்பு", days: "7 - 10 நாட்கள்", desc: "பரிந்துரைக்கப்பட்ட சிகிச்சையை இன்று பயன்படுத்தினால், ஒரு வாரத்திற்குள் புதிய ஆரோக்கியமான இலைகள் தோன்றும்." }, plan: { title: "சரிபார்க்கப்பட்ட சிகிச்சை திட்டம்", subtitle: "ICAR அங்கீகரிக்கப்பட்ட நெறிமுறை", medicine: { type: "இரசாயன பூஞ்சைக் கொல்லி", dosage: "அளவு / ஏக்கர்", water: "தண்ணீர் / ஏக்கர்", important: "முக்கியமானது:", warning: "அறுவடைக்கு முன் குறைந்தது 5 நாட்கள் காத்திருக்கவும். பாதுகாப்பு கியர் அணியுங்கள்." }, why: { title: "இதை ஏன் பரிந்துரைக்கிறோம்", desc: "மாங்கோசெப் சிறந்த தடுப்பு நடவடிக்கையை வழங்கும் பூஞ்சைக் கொல்லியாகும்." }, actions: { add: "இன்றைய பணிகளில் சேர்க்கவும்", order: "மருந்தை ஆர்டர் செய்யவும்" } }
  },
  te: {
    loading: "నివేదిక లోడ్ అవుతోంది...", error: { title: "నివేదిక లోడ్ విఫలమైంది", desc: "నివేదిక చెల్లనిది కావచ్చు.", back: "డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి" }, title: "విశ్లేషణ నివేదిక", subtitle: "పంట విశ్లేషణ", verified: "AI ధృవీకరించబడింది", score: "స్కోర్", status: { healthy: "ఆరోగ్యకరమైన పంట", severity: "తీవ్రత", healthyTitle: "పంట ఆరోగ్యంగా కనిపిస్తోంది", healthyDesc: "ఎలాంటి వ్యాధులు లేదా తెగుళ్లు కనుగొనబడలేదు.", detected: "గుర్తించబడింది", diseaseDesc: "మేము ఇన్ఫెక్షన్ సంకేతాలను గుర్తించాము. తక్షణ చర్య అవసరం." }, confidence: { title: "AI విశ్వాస విశ్లేషణ", disease: "వ్యాధి కనుగొనబడింది.", pest: "తెగులు కనుగొనబడింది.", none: "AI ద్వారా ఎటువంటి సమస్యలు గుర్తించబడలేదు." }, recovery: { title: "రికవరీ అంచనా", label: "ఆశించిన రికవరీ", days: "7 - 10 రోజులు", desc: "ఈ రోజు సిఫార్సు చేయబడిన చికిత్స వర్తింపజేస్తే, ఒక వారంలో కొత్త ఆరోగ్యకరమైన ఆకులు కనిపిస్తాయి." }, plan: { title: "ధృవీకరించబడిన చికిత్స ప్రణాళిక", subtitle: "ICAR ఆమోదిత ప్రోటోకాల్", medicine: { type: "రసాయన శిలీంద్ర సంహారిణి", dosage: "మోతాదు / ఎకరం", water: "నీరు / ఎకరం", important: "ముఖ్యమైనది:", warning: "కోతకు ముందు కనీసం 5 రోజులు వేచి ఉండండి. రక్షణ గేర్ ధరించండి." }, why: { title: "మేము దీనిని ఎందుకు సిఫార్సు చేస్తున్నాము", desc: "మాంకోజెబ్ అద్భుతమైన నివారణ చర్యను అందించే శిలీంద్ర సంహారిణి." }, actions: { add: "నేటి పనులకు జోడించండి", order: "మందు ఆర్డర్ చేయండి" } }
  },
  gu: {
    loading: "રિપોર્ટ લોડ થઈ રહ્યો છે...", error: { title: "રિપોર્ટ લોડ નિષ્ફળ", desc: "રિપોર્ટ અમાન્ય હોઈ શકે છે.", back: "ડેશબોર્ડ પર પાછા ફરો" }, title: "વિશ્લેષણ રિપોર્ટ", subtitle: "પાક વિશ્લેષણ", verified: "AI ચકાસાયેલ", score: "સ્કોર", status: { healthy: "તંદુરસ્ત પાક", severity: "ગંભીરતા", healthyTitle: "પાક તંદુરસ્ત લાગે છે", healthyDesc: "કોઈ રોગો અથવા જીવાતો મળી નથી.", detected: "શોધાયેલ", diseaseDesc: "અમને ચેપના સંકેતો મળ્યા છે. તાત્કાલિક પગલાં લેવાની જરૂર છે." }, confidence: { title: "AI વિશ્વાસ વિશ્લેષણ", disease: "રોગ મળ્યો.", pest: "જીવાત મળી.", none: "AI દ્વારા કોઈ સમસ્યા જોવા મળી નથી." }, recovery: { title: "પુનઃપ્રાપ્તિ અંદાજ", label: "અપેક્ષિત પુનઃપ્રાપ્તિ", days: "7 - 10 દિવસ", desc: "જો આજે ભલામણ કરેલ સારવાર લાગુ કરવામાં આવે, તો એક અઠવાડિયામાં નવા તંદુરસ્ત પાંદડા દેખાશે." }, plan: { title: "ચકાસાયેલ સારવાર યોજના", subtitle: "ICAR માન્ય પ્રોટોકોલ", medicine: { type: "રાસાયણિક ફૂગનાશક", dosage: "ડોઝ / એકર", water: "પાણી / એકર", important: "મહત્વપૂર્ણ:", warning: "લણણી પહેલા ઓછામાં ઓછા 5 દિવસ રાહ જુઓ. રક્ષણાત્મક ગિયર પહેરો." }, why: { title: "અમે આની ભલામણ શા માટે કરીએ છીએ", desc: "મેન્કોઝેબ એક ફૂગનાશક છે જે ઉત્તમ નિવારક પગલાં પૂરા પાડે છે." }, actions: { add: "આજના કાર્યોમાં ઉમેરો", order: "દવા ઓર્ડર કરો" } }
  },
  kn: {
    loading: "ವರದಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...", error: { title: "ವರದಿ ಲೋಡ್ ವಿಫಲವಾಗಿದೆ", desc: "ವರದಿ ಅಮಾನ್ಯವಾಗಿರಬಹುದು.", back: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ" }, title: "ವಿಶ್ಲೇಷಣೆ ವರದಿ", subtitle: "ಬೆಳೆ ವಿಶ್ಲೇಷಣೆ", verified: "AI ಪರಿಶೀಲಿಸಲಾಗಿದೆ", score: "ಸ್ಕೋರ್", status: { healthy: "ಆರೋಗ್ಯಕರ ಬೆಳೆ", severity: "ತೀವ್ರತೆ", healthyTitle: "ಬೆಳೆ ಆರೋಗ್ಯಕರವಾಗಿ ಕಾಣುತ್ತದೆ", healthyDesc: "ಯಾವುದೇ ರೋಗಗಳು ಅಥವಾ ಕೀಟಗಳು ಕಂಡುಬಂದಿಲ್ಲ.", detected: "ಪತ್ತೆಯಾಗಿದೆ", diseaseDesc: "ನಾವು ಸೋಂಕಿನ ಲಕ್ಷಣಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿದ್ದೇವೆ. ತಕ್ಷಣದ ಕ್ರಮ ಅಗತ್ಯವಿದೆ." }, confidence: { title: "AI ವಿಶ್ವಾಸಾರ್ಹತೆ ವಿಶ್ಲೇಷಣೆ", disease: "ರೋಗ ಪತ್ತೆಯಾಗಿದೆ.", pest: "ಕೀಟ ಪತ್ತೆಯಾಗಿದೆ.", none: "AI ನಿಂದ ಯಾವುದೇ ಸಮಸ್ಯೆ ಕಂಡುಬಂದಿಲ್ಲ." }, recovery: { title: "ಚೇತರಿಕೆ ಅಂದಾಜು", label: "ನಿರೀಕ್ಷಿತ ಚೇತರಿಕೆ", days: "7 - 10 ದಿನಗಳು", desc: "ಇಂದು ಶಿಫಾರಸು ಮಾಡಿದ ಚಿಕಿತ್ಸೆಯನ್ನು ಅನ್ವಯಿಸಿದರೆ, ಒಂದು ವಾರದೊಳಗೆ ಹೊಸ ಆರೋಗ್ಯಕರ ಎಲೆಗಳು ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ." }, plan: { title: "ಪರಿಶೀಲಿಸಿದ ಚಿಕಿತ್ಸಾ ಯೋಜನೆ", subtitle: "ICAR ಅನುಮೋದಿತ ಪ್ರೋಟೋಕಾಲ್", medicine: { type: "ರಾಸಾಯನಿಕ ಶಿಲೀಂಧ್ರನಾಶಕ", dosage: "ಡೋಸೇಜ್ / ಎಕರೆ", water: "ನೀರು / ಎಕರೆ", important: "ಪ್ರಮುಖ:", warning: "ಕೊಯ್ಲು ಮಾಡುವ ಮೊದಲು ಕನಿಷ್ಠ 5 ದಿನ ಕಾಯಿರಿ. ರಕ್ಷಣಾತ್ಮಕ ಗೇರ್ ಧರಿಸಿ." }, why: { title: "ನಾವು ಇದನ್ನು ಏಕೆ ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ", desc: "ಮ್ಯಾಂಕೋಜೆಬ್ ಅತ್ಯುತ್ತಮ ತಡೆಗಟ್ಟುವ ಕ್ರಮವನ್ನು ಒದಗಿಸುವ ಶಿಲೀಂಧ್ರನಾಶಕವಾಗಿದೆ." }, actions: { add: "ಇಂದಿನ ಕಾರ್ಯಗಳಿಗೆ ಸೇರಿಸಿ", order: "ಔಷಧಿಯನ್ನು ಆದೇಶಿಸಿ" } }
  },
  pa: {
    loading: "ਰਿਪੋਰਟ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...", error: { title: "ਰਿਪੋਰਟ ਲੋਡ ਅਸਫਲ", desc: "ਰਿਪੋਰਟ ਅਵੈਧ ਹੋ ਸਕਦੀ ਹੈ।", back: "ਡੈਸ਼ਬੋਰਡ 'ਤੇ ਵਾਪਸ ਜਾਓ" }, title: "ਵਿਸ਼ਲੇਸ਼ਣ ਰਿਪੋਰਟ", subtitle: "ਫਸਲ ਵਿਸ਼ਲੇਸ਼ਣ", verified: "AI ਪ੍ਰਮਾਣਿਤ", score: "ਸਕੋਰ", status: { healthy: "ਸਿਹਤਮੰਦ ਫਸਲ", severity: "ਗੰਭੀਰਤਾ", healthyTitle: "ਫਸਲ ਸਿਹਤਮੰਦ ਲੱਗਦੀ ਹੈ", healthyDesc: "ਕੋਈ ਬਿਮਾਰੀਆਂ ਜਾਂ ਕੀੜੇ ਨਹੀਂ ਮਿਲੇ।", detected: "ਪਤਾ ਲੱਗਾ", diseaseDesc: "ਅਸੀਂ ਲਾਗ ਦੇ ਲੱਛਣਾਂ ਦਾ ਪਤਾ ਲਗਾਇਆ ਹੈ। ਤੁਰੰਤ ਕਾਰਵਾਈ ਦੀ ਲੋੜ ਹੈ।" }, confidence: { title: "AI ਵਿਸ਼ਵਾਸ ਵਿਸ਼ਲੇਸ਼ਣ", disease: "ਬਿਮਾਰੀ ਮਿਲੀ।", pest: "ਕੀੜਾ ਮਿਲਿਆ।", none: "AI ਦੁਆਰਾ ਕੋਈ ਸਮੱਸਿਆ ਨਹੀਂ ਲੱਭੀ।" }, recovery: { title: "ਰਿਕਵਰੀ ਅਨੁਮਾਨ", label: "ਉਮੀਦ ਕੀਤੀ ਰਿਕਵਰੀ", days: "7 - 10 ਦਿਨ", desc: "ਜੇ ਅੱਜ ਸਿਫ਼ਾਰਸ਼ ਕੀਤੇ ਇਲਾਜ ਨੂੰ ਲਾਗੂ ਕੀਤਾ ਜਾਂਦਾ ਹੈ, ਤਾਂ ਇੱਕ ਹਫ਼ਤੇ ਦੇ ਅੰਦਰ ਨਵੇਂ ਸਿਹਤਮੰਦ ਪੱਤੇ ਦਿਖਾਈ ਦੇਣੇ ਚਾਹੀਦੇ ਹਨ।" }, plan: { title: "ਪ੍ਰਮਾਣਿਤ ਇਲਾਜ ਯੋਜਨਾ", subtitle: "ICAR ਪ੍ਰਵਾਨਿਤ ਪ੍ਰੋਟੋਕੋਲ", medicine: { type: "ਰਸਾਇਣਕ ਉੱਲੀਨਾਸ਼ਕ", dosage: "ਖੁਰਾਕ / ਏਕੜ", water: "ਪਾਣੀ / ਏਕੜ", important: "ਮਹੱਤਵਪੂਰਨ:", warning: "ਵਾਢੀ ਤੋਂ ਪਹਿਲਾਂ ਘੱਟੋ-ਘੱਟ 5 ਦਿਨ ਉਡੀਕ ਕਰੋ। ਸੁਰੱਖਿਆ ਗੇਅਰ ਪਹਿਨੋ।" }, why: { title: "ਅਸੀਂ ਇਸਦੀ ਸਿਫ਼ਾਰਸ਼ ਕਿਉਂ ਕਰਦੇ ਹਾਂ", desc: "ਮੈਨਕੋਜ਼ੇਬ ਇੱਕ ਉੱਲੀਨਾਸ਼ਕ ਹੈ ਜੋ ਸ਼ਾਨਦਾਰ ਰੋਕਥਾਮ ਕਾਰਵਾਈ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।" }, actions: { add: "ਅੱਜ ਦੇ ਕੰਮਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ", order: "ਦਵਾਈ ਆਰਡਰ ਕਰੋ" } }
  },
  ml: {
    loading: "റിപ്പോർട്ട് ലോഡ് ചെയ്യുന്നു...", error: { title: "റിപ്പോർട്ട് ലോഡ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു", desc: "റിപ്പോർട്ട് അസാധുവാകാം.", back: "ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക" }, title: "വിശകലന റിപ്പോർട്ട്", subtitle: "വിള വിശകലനം", verified: "AI പരിശോധിച്ചു", score: "സ്കോർ", status: { healthy: "ആരോഗ്യമുള്ള വിള", severity: "തീവ്രത", healthyTitle: "വിള ആരോഗ്യകരമാണെന്ന് തോന്നുന്നു", healthyDesc: "രോഗങ്ങളോ കീടങ്ങളോ കണ്ടെത്തിയില്ല.", detected: "കണ്ടെത്തി", diseaseDesc: "ഞങ്ങൾ അണുബാധയുടെ ലക്ഷണങ്ങൾ കണ്ടെത്തി. അടിയന്തര നടപടി ആവശ്യമാണ്." }, confidence: { title: "AI ആത്മവിശ്വാസ വിശകലനം", disease: "രോഗം കണ്ടെത്തി.", pest: "കീടത്തെ കണ്ടെത്തി.", none: "AI ഒരു പ്രശ്നവും കണ്ടെത്തിയില്ല." }, recovery: { title: "വീണ്ടെടുക്കൽ എസ്റ്റിമേറ്റ്", label: "പ്രതീക്ഷിക്കുന്ന വീണ്ടെടുക്കൽ", days: "7 - 10 ദിവസം", desc: "ശുപാർശ ചെയ്യുന്ന ചികിത്സ ഇന്ന് പ്രയോഗിച്ചാൽ, ഒരാഴ്ചയ്ക്കുള്ളിൽ പുതിയ ആരോഗ്യകരമായ ഇലകൾ പ്രത്യക്ഷപ്പെടും." }, plan: { title: "പരിശോധിച്ച ചികിത്സാ പദ്ധതി", subtitle: "ICAR അംഗീകരിച്ച പ്രോട്ടോക്കോൾ", medicine: { type: "രാസ കുമിൾനാശിനി", dosage: "അളവ് / ഏക്കർ", water: "വെള്ളം / ഏക്കർ", important: "പ്രധാനം:", warning: "വിളവെടുപ്പിന് മുമ്പ് കുറഞ്ഞത് 5 ദിവസം കാത്തിരിക്കുക. സംരക്ഷണ ഗിയർ ധരിക്കുക." }, why: { title: "എന്തുകൊണ്ടാണ് ഞങ്ങൾ ഇത് ശുപാർശ ചെയ്യുന്നത്", desc: "മാൻകോസെബ് മികച്ച പ്രതിരോധ പ്രവർത്തനങ്ങൾ നൽകുന്ന ഒരു കുമിൾനാശിനിയാണ്." }, actions: { add: "ഇന്നത്തെ ടാസ്ക്കുകളിലേക്ക് ചേർക്കുക", order: "മരുന്ന് ഓർഡർ ചെയ്യുക" } }
  }
};

const localesDir = path.join(__dirname, 'src', 'locales');

Object.keys(newReport).forEach(lang => {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const existing = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    existing.report = newReport[lang];
    fs.writeFileSync(filePath, JSON.stringify(existing, null, 2));
  }
});

console.log("Appended report page translations!");
