from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum

class Severity(str, Enum):
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class WaterStatus(str, Enum):
    DRY = "dry"
    NORMAL = "normal"
    EXCESS = "excess"
    WATERLOGGED = "waterlogged"

class BoundingBox(BaseModel):
    ymin: float
    xmin: float
    ymax: float
    xmax: float

class DetectedIssue(BaseModel):
    name: str = Field(..., description="Name of the detected disease or pest")
    confidence: float = Field(..., ge=0.0, le=1.0, description="AI confidence score")
    severity: Severity = Field(..., description="Severity level of the issue")
    affected_area_percentage: float = Field(..., ge=0.0, le=100.0, description="Estimated percentage of crop/leaf area affected")
    bounding_boxes: List[BoundingBox] = Field(default_factory=list, description="Coordinates of detected lesions or pests")
    notes: Optional[str] = Field(None, description="Agronomist notes generated by AI")

class Recommendation(BaseModel):
    medicine_name: str
    active_ingredient: str
    dosage_quantity: float
    dosage_unit: str
    water_litres_per_acre: float
    instructions: str

class AIPipelineOutput(BaseModel):
    crop_identified: str = Field(..., description="The name of the detected crop")
    crop_confidence: float = Field(..., ge=0.0, le=1.0)
    detected_diseases: List[DetectedIssue] = Field(default_factory=list)
    detected_pests: List[DetectedIssue] = Field(default_factory=list)
    leaf_condition_score: int = Field(..., ge=0, le=100)
    color_analysis_score: int = Field(..., ge=0, le=100)
    water_status: WaterStatus
    overall_confidence: float = Field(..., ge=0.0, le=1.0)
    health_score: Optional[int] = Field(None, ge=0, le=100, description="Calculated overall crop health score")
    recommendations: List[Recommendation] = Field(default_factory=list)
